Traceback (most recent call last):
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
db = createCustomDatabase()

solution = AqueousPhase()

system = ChemicalSystem(db, solution)

state = ChemicalState(system)
state.set("H2O", 1.0, "kg")

equilibrate(state)

print(state)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_2139/3947657458.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mdb[0m [0;34m=[0m [0mcreateCustomDatabase[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0msolution[0m [0;34m=[0m [0mAqueousPhase[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0msystem[0m [0;34m=[0m [0mChemicalSystem[0m[0;34m([0m[0mdb[0m[0;34m,[0m [0msolution[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/tmp/ipykernel_2139/1870690507.py[0m in [0;36mcreateCustomDatabase[0;34m()[0m
[1;32m      2[0m     [0melements[0m [0;34m=[0m [0mcreateElementList[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mspecies[0m [0;34m=[0m [0mcreateSpeciesList[0m[0;34m([0m[0melements[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m     [0;32mreturn[0m [0mDatabase[0m[0;34m([0m[0mspecies[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mTypeError[0m: object of type 'reaktoro.reaktoro4py.SpeciesList' has no len()
TypeError: object of type 'reaktoro.reaktoro4py.SpeciesList' has no len()

