Traceback (most recent call last):
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/allan/miniconda3/envs/reaktoro-jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from reaktoro import *

db = PhreeqcDatabase("phreeqc.dat")

solution = AqueousPhase(speciate("H O Na Cl C Ca Mg"))
solution.setActivityModel(ActivityModelIdealAqueous())

gases = GaseousPhase("CO2(g) H2O(g)")
gases.setActivityModel(ActivityModelIdealGas())

solidsolution = MineralPhase("Siderite Rhodochrosite")
solidsolution.setActivityModel(ActivityModelIdealSolution())

ionexchange = IonExchangePhase("NaX CaX2")
ionexchange.setActivityModel(ActivityModelIdealIonExchange())

system = ChemicalSystem(db, solution, gases, solidsolution, ionexchange)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_12598/1777631571.py[0m in [0;36m<module>[0;34m[0m
[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0msolidsolution[0m [0;34m=[0m [0mMineralPhase[0m[0;34m([0m[0;34m"Siderite Rhodochrosite"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 12[0;31m [0msolidsolution[0m[0;34m.[0m[0msetActivityModel[0m[0;34m([0m[0mActivityModelIdealSolution[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     13[0m [0;34m[0m[0m
[1;32m     14[0m [0mionexchange[0m [0;34m=[0m [0mIonExchangePhase[0m[0;34m([0m[0;34m"NaX CaX2"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: ActivityModelIdealSolution(): incompatible function arguments. The following argument types are supported:
    1. (arg0: reaktoro.reaktoro4py.StateOfMatter) -> Callable[[reaktoro.reaktoro4py.SpeciesList], reaktoro.reaktoro4py.ActivityModel]

Invoked with: 
TypeError: ActivityModelIdealSolution(): incompatible function arguments. The following argument types are supported:
    1. (arg0: reaktoro.reaktoro4py.StateOfMatter) -> Callable[[reaktoro.reaktoro4py.SpeciesList], reaktoro.reaktoro4py.ActivityModel]

Invoked with: 

